openapi: 3.0.0 # OpenAPI-Version (erlaubte Features und Syntax)
info: # Allgemeine Infos zur Schnittstelle
  title: EDI@Energy API-Webdienst zur Übermittlung von Lokationsbündeln mit Nennung der zugeordneten Marktpartnern im Rahmen von Netzbetreiberwechselprozessen
  version: 1.0.0
  description: Mit diesen API-Webdienst wird die Übermittlung von Lokationsbündeln (wie im locationBundleV1 beschrieben) mit zusätzlicher Nennung der zugeordneten Marktpartnern im Rahmen von Netzbetreiberwechselprozessen umgesetzt. Dabei werden die Marktpartner genannt, die zum Zeitpunkt des Versendens der Nachricht dem NBA für den Zeitpunkt des Netzbetreiberwechsels vorliegen mitgeteilt. Eine Abbildung in Zeitscheiben findet für die Marktpartnerzuordnung nicht statt

paths:
  /locationBundle/v1:
    post:
      summary: Übermittlung von Lokationsbündeln mit Nennung der zugeordneten Marktpartnern im Rahmen von Netzbetreiberwechselprozessen
      description: Übermittlung von Lokationsbündeln mit Nennung der zugeordneten Marktpartnern im Rahmen von Netzbetreiberwechselprozessen
      tags:
        - Übermittlung von Lokationsbündeln mit Nennung der zugeordneten Marktpartnern im Rahmen von Netzbetreiberwechselprozessen
      parameters:
      - name: transactionId
        in: header
        description: Externe Transaktions-Id zur eindeutigen Identifikation des Aufrufs.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/header/transactionId.yaml#/components/schemas/transactionId'
      - name: creationDateTime
        in: header
        description: Zeitpunkt an dem der Aufruf erstellt wurde
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/dateAndTime/dateTime.yaml#/components/schemas/dateTime'
      - name: initialTransactionId
        in: header
        description: Zur Angabe des Idempotenzschlüssels im Falle eines Retry.
        required: false
        style: simple
        explode: false
        schema:
          $ref: '../../schema/header/initialTransactionId.yaml#/components/schemas/initialTransactionId'
      - name: testFlag
        in: query
        description: "Angabe, ob es sich bei dem Aufruf um einen Testaufruf handelt."
        required: true
        style: form
        explode: false
        schema:
          $ref: '../../schema/header/testFlag.yaml#/components/schemas/testFlag'
      requestBody:
        content:
         application/json:
           schema:
             $ref: '../../schema/masterData/locationBundleNetworkOperatorChange.yaml#/components/schemas/locationBundleNetworkOperatorChange'
      responses:
        "202":
          description: accepted
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "405":
          description: Method not allowed
        "500":
          description: Internal Server Error