openapi: 3.0.0 # OpenAPI-Version (erlaubte Features und Syntax)
info: # Allgemeine Infos zur Schnittstelle
  title: EDI@Energy API-Webdienst zur Übermittlung von Clearings zu Energielokationsbündeln mehrerer Marktlokationen
  version: 1.0.0
  description: Mit diesen API-Webdienst wird die Übermittlung von Clearings zu Energielokationsbündeln mehrerer Marktlokationen umgesetzt. Dabei kann der Datenstand im IT System des Berechtigten dargestellt werden und zudem wenn erforderlich die Erwartung an die Daten, wie der Berechtigte sie gerne vom Verantwortlichen bekommen würde. Dieses Bündel wird benötigt, um dem Markt mitzuteilen, welche Marktlokationen Bestanteil eines Energielokationsbündels sind, das zum Beispiel für Energie-Sharing gebildet wurde. Im Fall von Energie-Sharing wird die erzeugende Marktlokation genannt, welche die Energie bereitstellt und zudem alle verbrauchenden Marktlokationen, die im Rahmen von Energie-Sharing Energie von der genannten erzeugenden Marktlokation beziehen. Die Übermittlung erfolgt in Zeitscheiben, um hinzukommende oder abgehende verbrauchende Marktlokationen darstellen zu können.

paths:
  /locationBundle/v1:
    post:
      summary: Übermittlung von Clearings zu Energielokationsbündeln mehrerer Marktlokationen
      description: Übermittlung von Clearings zu Energielokationsbündeln mehrerer Marktlokationen
      tags:
        - Übermittlung von Energielokationsbündeln mehrerer Marktlokationen
      parameters:
      - name: transactionId
        in: header
        description: Externe Transaktions-Id zur eindeutigen Identifikation des Aufrufs.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/header/transactionId.yaml#/components/schemas/transactionId'
      - name: creationDateTime
        in: header
        description: Zeitpunkt an dem der Aufruf erstellt wurde
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/dateAndTime/dateTime.yaml#/components/schemas/dateTime'
      - name: initialTransactionId
        in: header
        description: Zur Angabe des Idempotenzschlüssels im Falle eines Retry.
        required: false
        style: simple
        explode: false
        schema:
          $ref: '../../schema/header/initialTransactionId.yaml#/components/schemas/initialTransactionId'
      - name: testFlag
        in: query
        description: "Angabe, ob es sich bei dem Aufruf um einen Testaufruf handelt."
        required: true
        style: form
        explode: false
        schema:
          $ref: '../../schema/header/testFlag.yaml#/components/schemas/testFlag'
      requestBody:
        content:
         application/json:
           schema:
             $ref: '../../schema/masterData/locationBundleEnergyClearing.yaml#/components/schemas/locationBundleEnergyClearing'
      responses:
        "202":
          description: accepted
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "405":
          description: Method not allowed
        "500":
          description: Internal Server Error