openapi: 3.0.0 # OpenAPI-Version (erlaubte Features und Syntax)
info: # Allgemeine Infos zur Schnittstelle
  title: EDI@Energy API-Webdienst zur Übermittlung einer Übersicht von Lokation-IDs
  version: 1.0.0
  description: "Mit diesem API-Webdienst werden alle mit einer Marktlokation referenzierten Lokationen (Netzlokation, Messlokation(en), Tranche(n), Technische Ressource(n), Steuerbare Ressource(n), etc.) und den jeweils zugeordneten Marktpartner übermittelt. Zudem werden weitere Eigenschfaten der Marktlokation übermittelt." 
paths:
  /overview/overviewOfLocationsOfOneMarketLocation/v1:
    post:
      summary: Übermittlung der Übersicht aller einer Marktlokation zugeordneten Lokationen.
      description: Übermittlung der Übersicht aller einer Marktlokation zugeordneten Lokationen.
      tags:
        -  Übermittlung der Übersicht aller einer Marktlokation zugeordneten Lokationen.
      parameters:
      - name: transactionId
        in: header
        description: Externe Transaktions-Id zur eindeutigen Identifikation der Anfrage des sendenden Marktpartners.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/header/transactionId.yaml#/components/schemas/transactionId'
      - name: creationDateTime
        in: header
        description: Zeitpunkt an dem der Aufruf erstellt wurde
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/dateAndTime/dateTime.yaml#/components/schemas/dateTime'
      - name: initialTransactionId
        in: header
        description: Zur Angabe des Idempotenzschlüssels im Falle eines Retry.
        required: false
        style: simple
        explode: false
        schema:
          $ref: '../../schema/header/initialTransactionId.yaml#/components/schemas/initialTransactionId'
      - name: referenceId
        in: query
        description: "Externe Vorgangsreferenz zur eindeutigen Identifikation der ursprünglichen Anfrage."
        required: true
        style: form
        explode: false
        schema:
          $ref: '../../schema/header/referenceId.yaml#/components/schemas/referenceId'
      - name: testFlag
        in: query
        description: "Angabe, ob es sich bei dem Aufruf um einen Testaufruf handelt."
        required: true
        style: form
        explode: false
        schema:
          $ref: '../../schema/header/testFlag.yaml#/components/schemas/testFlag'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../schema/overviewOfLocationsOfOneMarketLocation.yaml#/components/schemas/overviewOfLocationsOfOneMarketLocation'
      responses:
        "202":
          description: accepted
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "405":
          description: Method not allowed
        "500":
          description: Internal Server Error
