openapi: 3.0.0 # OpenAPI-Version (erlaubte Features und Syntax)
info: # Allgemeine Infos zur Schnittstelle
  title: EDI@Energy API-Webdienst zur Übermittlung der Übersicht und den ausgerollten Schaltzeiten
  version: 1.0.0
  description: Mit diesem API-Webdienst wird die Übermittlung der Übersicht und den ausgerollten Schaltzeiten umgesetzt.

paths:
  /switchingTime/overview/v1:
    post:
      summary: Übermittlung der Übersicht der Schaltzeiten
      description: Übermittlung der Übersicht der Schaltzeiten
      tags:
        - Übermittlung der Übersicht der Schaltzeiten
      parameters:
      - name: transactionId
        in: header
        description: Externe Transaktions-Id zur eindeutigen Identifikation der Übermittlung der Übersicht der Schaltzeiten des sendenden Marktpartners.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/header/transactionId.yaml#/components/schemas/transactionId'
      - name: creationDateTime
        in: header
        description: Zeitpunkt an dem der Aufruf erstellt wurde
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/dateAndTime/dateTime.yaml#/components/schemas/dateTime'
      - name: initialTransactionId
        in: header
        description: Zur Angabe des Idempotenzschlüssels im Falle eines Retry.
        required: false
        style: simple
        explode: false
        schema:
          $ref: '../../schema/header/initialTransactionId.yaml#/components/schemas/initialTransactionId'
      - name: testFlag
        in: query
        description: "Angabe, ob es sich bei dem Aufruf um einen Testaufruf handelt."
        required: true
        style: form
        explode: false
        schema:
          $ref: '../../schema/header/testFlag.yaml#/components/schemas/testFlag'
      requestBody:
        content:
         application/json:
           schema:
             $ref: '../../schema/definitions/overviewSwitchingTime.yaml#/components/schemas/overviewSwitchingTime'
      responses:
        "202":
          description: accepted
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "405":
          description: Method not allowed
        "500":
          description: Internal Server Error1

  /switchingTime/yearlyRollout/v1:
    post:
      summary: Übermittlung einer jährlich ausgerollten Schaltzeiten
      description: Übermittlung einer jährlich ausgerollten Schaltzeiten
      tags:
        - Übermittlung einer jährlich ausgerollten Schaltzeiten
      parameters:
      - name: transactionId
        in: header
        description: Externe Transaktions-Id zur eindeutigen Identifikation der Übermittlung einer jährlich ausgerollten Schaltzeiten.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/header/transactionId.yaml#/components/schemas/transactionId'
      - name: creationDateTime
        in: header
        description: Zeitpunkt an dem der Aufruf erstellt wurde
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/dateAndTime/dateTime.yaml#/components/schemas/dateTime'
      - name: initialTransactionId
        in: header
        description: Zur Angabe des Idempotenzschlüssels im Falle eines Retry.
        required: false
        style: simple
        explode: false
        schema:
          $ref: '../../schema/header/initialTransactionId.yaml#/components/schemas/initialTransactionId'
      - name: testFlag
        in: query
        description: "Angabe, ob es sich bei dem Aufruf um einen Testaufruf handelt."
        required: true
        style: form
        explode: false
        schema:
          $ref: '../../schema/header/testFlag.yaml#/components/schemas/testFlag'
      requestBody:
        content:
         application/json:
           schema:
             $ref: '../../schema/definitions/yearlyRolloutSwitchingTime.yaml#/components/schemas/yearlyRolloutSwitchingTime'
      responses:
        "202":
          description: accepted
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "405":
          description: Method not allowed
        "500":
          description: Internal Server Error1

  /switchingTime/uniqueRollout/v1:
    post:
      summary: Übermittlung einer einmalig ausgerollten Schaltzeiten
      description: Übermittlung einer einmalig ausgerollten Schaltzeiten
      tags:
        - Übermittlung einer einmalig ausgerollten Schaltzeiten
      parameters:
      - name: transactionId
        in: header
        description: Externe Transaktions-Id zur eindeutigen Identifikation der Übermittlung einer einmlaig ausgerollten Schaltzeiten.
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/header/transactionId.yaml#/components/schemas/transactionId'
      - name: creationDateTime
        in: header
        description: Zeitpunkt an dem der Aufruf erstellt wurde
        required: true
        style: simple
        explode: false
        schema:
          $ref: '../../schema/dateAndTime/dateTime.yaml#/components/schemas/dateTime'
      - name: initialTransactionId
        in: header
        description: Zur Angabe des Idempotenzschlüssels im Falle eines Retry.
        required: false
        style: simple
        explode: false
        schema:
          $ref: '../../schema/header/initialTransactionId.yaml#/components/schemas/initialTransactionId'
      - name: testFlag
        in: query
        description: "Angabe, ob es sich bei dem Aufruf um einen Testaufruf handelt."
        required: true
        style: form
        explode: false
        schema:
          $ref: '../../schema/header/testFlag.yaml#/components/schemas/testFlag'
      requestBody:
        content:
         application/json:
           schema:
             $ref: '../../schema/definitions/uniqueRolloutSwitchingTime.yaml#/components/schemas/uniqueRolloutSwitchingTime'
      responses:
        "202":
          description: accepted
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "405":
          description: Method not allowed
        "500":
          description: Internal Server Error1
 